openapi: 3.0.3
info:
  title: Image Resizer API
  version: 1.0.0
  description: Simple health check and image resize/format conversion service.

servers:
  - url: http://localhost:3000
    description: Local dev

paths:
  /health:
    get:
      summary: Health check
      description: Returns basic service health status.
      responses:
        "200":
          description: Service is healthy.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /image/{name}:
    get:
      summary: Get (optionally resized) image
      description: >
        Returns an image by name.  
        If `width` and/or `height` are provided, the image is resized.  
        If `format` is provided, the image is converted to that format.  
        If width/height/format exactly match the original image, the original file is returned.
      parameters:
        - name: name
          in: path
          required: true
          description: Image file name (with or without extension).
          schema:
            type: string
            example: cat.jpg
        - name: width
          in: query
          required: false
          description: >
            Desired width in pixels. If omitted, the original width is used.
          schema:
            type: integer
            minimum: 1
            example: 800
        - name: height
          in: query
          required: false
          description: >
            Desired height in pixels. If omitted, the original height is used.
          schema:
            type: integer
            minimum: 1
            example: 600
        - name: format
          in: query
          required: false
          description: >
            Desired output format. If omitted, the original format is used.
            Supports `jpeg`, `png`, `webp`, `avif`. `jpg` is normalized to `jpeg`.
          schema:
            type: string
            enum: [jpeg, png, webp, avif, jpg]
            example: webp
      responses:
        "200":
          description: Image bytes.
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
            image/png:
              schema:
                type: string
                format: binary
            image/webp:
              schema:
                type: string
                format: binary
            image/avif:
              schema:
                type: string
                format: binary
        "400":
          description: Invalid query parameters (e.g. non-numeric width/height).
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                invalidWidth:
                  summary: Width must be a number
                  value:
                    error: Width must be a number
        "404":
          description: Image not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                notFound:
                  summary: Original image not found
                  value:
                    error: "Original image not found for 'cat.jpg'"
        "500":
          description: Server error while resizing/serving image.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                resizeError:
                  summary: Resize error
                  value:
                    error: Error resizing image

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Error resizing image
